### ISSUE TITLE
Windows doesn't work!

### ISSUE THREAD

**Issue by foowaa** [AgoraIO-Community/Agora-Electron-Quickstart#12]
OS: Windows 10
node: 8.16.1
`npm install` is OK.
When I `npm run dev`, the electron window is blank, and the devtools' console prints:
```
electron/js2c/asar.js:155 Uncaught Error: \\?\D:\codes\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.
\\?\D:\codes\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node
    at process.func [as dlopen] (electron/js2c/asar.js:155)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881)
    at Object.func [as .node] (electron/js2c/asar.js:155)
    at Module.load (internal/modules/cjs/loader.js:701)
    at tryModuleLoad (internal/modules/cjs/loader.js:633)
    at Function.Module._load (internal/modules/cjs/loader.js:625)
    at Module.require (internal/modules/cjs/loader.js:739)
    at require (internal/modules/cjs/helpers.js:14)
    at Object.<anonymous> (D:\codes\Agora-Elect…k\js\Api\index.js:6)
    at Object.<anonymous> (D:\codes\Agora-Elect…s\Api\index.js:3786)
```
What's the problem?

**Comment by plutoless** [comment]
Hi you will need to run npm install electron —arch=is32 to install 32bits electron

**Comment by foowaa** [comment]
Hi, I copy 'npm install electron --arch=is32`, and cmd prints:
```
PS D:\codes\Agora-Electron-Quickstart> npm install electron --arch=i32

> electron@5.0.8 postinstall D:\codes\Agora-Electron-Quickstart\node_modules\electron
> node install.js

Downloading tmp-16036-0-electron-v5.0.8-win32-i32.zip
Error: GET https://github.com/electron/electron/releases/download/v5.0.8/electron-v5.0.8-win32-i32.zip returned 404
D:\codes\Agora-Electron-Quickstart\node_modules\electron\install.js:49
  throw err
  ^

Error: Failed to find Electron v5.0.8 for win32-i32 at https://github.com/electron/electron/releases/download/v5.0.8/electron-v5.0.8-win32-i32.zip
    at Request.<anonymous> (D:\codes\Agora-Electron-Quickstart\node_modules\nugget\index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (D:\codes\Agora-Electron-Quickstart\node_modules\request\request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
npm WARN electron-webpack-quick-start@0.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@5.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@5.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\25679\AppData\Roaming\npm-cache\_logs\2019-10-01T02_42_29_989Z-debug.log
PS D:\codes\Agora-Electron-Quickstart> npm install electron —arch=is32
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "—arch=is32": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\25679\AppData\Roaming\npm-cache\_logs\2019-10-01T02_43_48_703Z-debug.log
```
How to solve?

**Comment by plutoless** [comment]
ia32 instead of i32

**Comment by foowaa** [comment]
alseo failed.
`npm install electron --arch=ia32`
```
PS D:\codes\Agora-Electron-Quickstart> npm install electron —arch=ia32
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "—arch=ia32": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\25679\AppData\Roaming\npm-cache\_logs\2019-10-01T03_38_43_405Z-debug.log
```

**Comment by plutoless** [comment]
Please check if you are input any Chinese characters

**Comment by foowaa** [comment]
I change the command tools in windows, and the problem is solved.
THX.
