### ISSUE TITLE
您好，程序运行时，显示空白屏幕，报错如下；

### ISSUE THREAD

**Issue by kongliya** [AgoraIO-Community/Agora-Electron-Quickstart#13]
Uncaught Error: \\?\d:\Electron\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.
\\?\d:\Electron\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (d:\Electron\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\js\Api\index.js:6:15)
    at Object.<anonymous> (d:\Electron\Agora-Electron-Quickstart\node_modules\agora-electron-sdk\js\Api\index.js:3786:3)

请问该如何解决呢？谢谢~

**Comment by kongliya** [comment]
emmmm....看到close里的解答了~ 骚瑞... 我去装试试￣□￣｜｜

**Comment by Matrixbirds** [comment]
可能是你安装的electron不是32位的 npm install -D electron --arch=ia32安装一下32位的
