### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by sidsharma27** [AgoraIO-Community/Agora-Electron-Quickstart#3]
Failed to run

$ npm run dev

electron-webpack-quick-start@0.0.0 dev /Users/jnci/git/Agora-Electron-Quickstart
electron-webpack dev

/Users/jnci/git/Agora-Electron-Quickstart/node_modules/electron-webpack/out/cli.js:37
args.push(...extraWebpackArgs);
^^^

SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:974:3

**Comment by menthays** [comment]
We cannot reproduce it on both Mac and Windows. But it seems that installation of dependencies broke, any error log during `npm install`?
