### ISSUE TITLE
Mac系统 打包失败

### ISSUE THREAD

**Issue by shaweigo** [AgoraIO-Community/Agora-Electron-Quickstart#33]
在Mac10.15.5系统上运行Agora-Electron-Vue工程的打包命令出错：
错误如下：
`open /Users/shawn/work/WebstormProjects/dxz-lvb-electron-vue/node_modules/agora-electron-sdk/node_modules/just-task/node_modules/undertaker/node_modules/es6-weak-map/node_modules/d/node_modules/es5-ext/node_modules/es6-symbol/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/es6-symbol/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-symbol/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/node_modules/es5-ext/node_modules/es6-iterator/node_modules/d/package.json: too many levels of symbolic links
github.com/develar/app-builder/pkg/node-modules.(*Collector).resolveDependency
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:192
github.com/develar/app-builder/pkg/node-modules.(*Collector).processDependencies
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:95
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:56
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72
github.com/develar/app-builder/pkg/node-modules.(*Collector).readDependencyTree
        /Volumes/data/Documents/app-builder/pkg/node-modules/nodeModuleCollector.go:72  
  ⨯ /Users/shawn/work/WebstormProjects/dxz-lvb-electron-vue/node_modules/_app-builder-bin@3.4.3@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                                        Error: /Users/shawn/work/WebstormProjects/dxz-lvb-electron-vue/node_modules/_app-builder-bin@3.4.3@app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                            at ChildProcess.<anonymous> (/Users/shawn/work/WebstormProjects/dxz-lvb-electron-vue/node_modules/_builder-util@21.2.0@builder-util/src/util.ts:239:14)
                                                                                                                                                                                            at Object.onceWrapper (events.js:412:26)
                                                                                                                                                                                            at ChildProcess.emit (events.js:305:20)
                                                                                                                                                                                            at maybeClose (internal/child_process.js:1028:16)
                                                                                                                                                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-webpack@1.0.0 dist: `cross-env NODE_ENV=production webpack --mode development && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-vue-webpack@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shawn/.npm/_logs/2020-06-03T09_11_50_571Z-debug.log
`

**Comment by plutoless** [comment]
@shaweigo 估计是打包的时候electron下载失败了，可以贴下完整的日志，或者配一下阿里的electron镜像
