### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kerolloz** [AgoraIO-Community/Agora-Electron-Quickstart#9]
when the app starts it only shows a blank screen

**Comment by plutoless** [comment]
any console logs?

**Comment by Mohamed-Fakhry** [comment]
**Console logs**
```
Uncaught Error: Cannot find module '../../build/Release/agora_node_ext'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename (/Users/mohamedfakhry/Desktop/Agora-Electron-Quickstart-master/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43)
    at Function.Module._load (internal/modules/cjs/loader.js:510)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (/Users/mohamedfakhry/Desktop/Agora-Electron-Quickstart-master/node_modules/agora-electron-sdk/js/Api/index.js:5)
    at Object.<anonymous> (/Users/mohamedfakhry/Desktop/Agora-Electron-Quickstart-master/node_modules/agora-electron-sdk/js/Api/index.js:2023)
    at Module._compile (internal/modules/cjs/loader.js:693)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)
    at Module.load (internal/modules/cjs/loader.js:602)
```

**Comment by plutoless** [comment]
Are you running this repository demo w/o modifications? Which platform are you running on? Windows?

**Comment by plutoless** [comment]
Sorry i see you are running on Mac. Could you pls double check if there's any file exists under /Users/mohamedfakhry/Desktop/Agora-Electron-Quickstart-master/node_modules/agora-electron-sdk/build/Release

**Comment by kerolloz** [comment]
I tried it on Linux

**Comment by Mohamed-Fakhry** [comment]
build/Release not exist
![image](https://user-images.githubusercontent.com/16600448/60248734-8e013800-98c3-11e9-92b2-682e19b40390.png)

**Comment by Mohamed-Fakhry** [comment]
we tried it on Linux and macOS

**Comment by plutoless** [comment]
Hi unfortunately our electron-sdk now only works on macOS + windows.
On MacOS if it's not working for you, could you pls remove node_modules/agora-electron-sdk, run npm i --verbose, and share the install logs with me?

**Comment by Mohamed-Fakhry** [comment]
Thank you work fine now, AgoraIO will support Linux ?

**Comment by plutoless** [comment]
there's no plan yet to support linux for now. @Mohamed-Fakhry

**Comment by ONwaiting** [comment]
Errors are also reported in Windows
![image](https://user-images.githubusercontent.com/42017322/66294293-368b5300-e91b-11e9-809e-3c1f5209df10.png)

**Comment by ONwaiting** [comment]
![image](https://user-images.githubusercontent.com/42017322/66295485-06917f00-e91e-11e9-9e33-ebbe87554471.png)

**Comment by plutoless** [comment]
@ONwaiting please take a look if the specified missing files actually exists in your file system or not

**Comment by kongliya** [comment]
> Errors are also reported in Windows
> ![image](https://user-images.githubusercontent.com/42017322/66294293-368b5300-e91b-11e9-809e-3c1f5209df10.png)

I have the same problem as you now.

**Comment by plutoless** [comment]
is your electron version 5.0.8 ? could you pls paste your npm install logs

**Comment by kongliya** [comment]
![image](https://user-images.githubusercontent.com/43961915/66455800-5c8d3080-ea9e-11e9-869e-778c2327858e.png)
我之前用npm一直安装失败，然后用yarn安装成功的，但是看到之前评论说必须npm安装 我现在重新安装报这个错了....

执行npm audit显示这个

![image](https://user-images.githubusercontent.com/43961915/66455877-93fbdd00-ea9e-11e9-9496-596dcb9d3337.png)
@plutoless

**Comment by plutoless** [comment]
这个应该不影响使用

**Comment by kongliya** [comment]
$ npm install

> agora-electron-sdk@2.9.0-hotfix.2 install d:\Agora-Electron-Quickstart\node_modules\agora-electron-sdk
> just install

[2:49:37 PM] ■ started 'install'
[2:49:37 PM] ■ Package Version: 2.9.0
[2:49:37 PM] ■ Platform: win32
[2:49:37 PM] ■ Electron Version: 5.0.8
[2:49:37 PM] ■   Download URL  :  http://download.agora.io/sdk/release/Electron-win32-2.9.0-5.0.8.zip 

[2:49:37 PM] ■ Downloading prebuilt C++ addon for Agora Electron SDK...

[2:49:37 PM] ■ finished 'install' in 0.04s



kl@DESKTOP-F0FH3QD MINGW64 /d/Agora-Electron-Quickstart (master)
$ npm run dev

> electron-webpack-quick-start@0.0.0 dev d:\Agora-Electron-Quickstart
> electron-webpack dev

┏ Renderer -------------------

  AttachConsole failed with error 6: �����Ч��

┗ ----------------------------
┏ Main -----------------------

  Hash: 3d300dc3761c8720b740
  Version: webpack 4.39.2
  Time: 740ms
  Built at: 2019-10-09 2:51:41 PM
    Asset    Size  Chunks             Chunk Names
  main.js  42 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] 582 bytes {main} [built]
  [./src/main/index.js] 1.51 KiB {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [electron-webpack/out/electron-main-hmr/HmrClient] external "electron-webpack/out/electron-main-hmr/HmrClient" 42 bytes {main} [built]
  [path] external "path" 42 bytes {main} [built]
  [source-map-support/source-map-support.js] external "source-map-support/source-map-support.js" 42 bytes {main} [built]
  [url] external "url" 42 bytes {main} [built]

┗ ----------------------------
┏ Renderer -------------------

  i ｢wds｣: Project is running at http://localhost:59885/

┗ ----------------------------
┏ Renderer -------------------

  i ｢wds｣: webpack output is served from /
  i ｢wds｣: Content not from webpack is served from d:\Agora-Electron-Quickstart\static, d:\Agora-Electron-Quickstart\dist\renderer-dll

┗ ----------------------------
┏ Renderer -------------------

  i ｢wdm｣: Hash: dee93e32d1102e1f2dc9
  Version: webpack 4.39.2
  Time: 3252ms
  Built at: 2019-10-09 2:51:49 PM
        Asset       Size    Chunks             Chunk Names
   index.html  425 bytes            [emitted]
  renderer.js   4.65 MiB  renderer  [emitted]  renderer
   styles.css    210 KiB  renderer  [emitted]  renderer
  Entrypoint renderer = styles.css renderer.js
  [1] multi (webpack)-dev-server/client?http://localhost:59885 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/renderer/index.js 64 bytes {renderer} [built]
  [./node_modules/bulma/css/bulma.css] 294 bytes {renderer} [built]
  [./node_modules/css-hot-loader/hotModuleReplacement.js] 3.05 KiB {renderer} [built]
  [./node_modules/css-hot-loader/node_modules/normalize-url/index.js] 3.85 KiB {renderer} [built]
  [./node_modules/lodash/debounce.js] 5.96 KiB {renderer} [built]
  [./node_modules/react-dom/index.js] 1.33 KiB {renderer} [built]
  [./node_modules/react/index.js] 190 bytes {renderer} [built]
  [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost:59885] (webpack)-dev-server/client?http://localhost:59885 4.29 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} [built]
  [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {renderer} [built]
  [./src/renderer/index.js] 218 bytes {renderer} [built]
      + 69 hidden modules
  Child html-webpack-plugin for "index.html":
  Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-2!src/renderer/index.css:
      Entrypoint mini-css-extract-plugin = *
      [./node_modules/css-loader/dist/cjs.js?!./src/renderer/index.css] ./node_modules/css-loader/dist/cjs.js??ref--6-2!./src/renderer/index.css 552 bytes {mini-css-extract-plugin} [built]
      [./node_modules/css-loader/dist/runtime/api.js] 2.61 KiB {mini-css-extract-plugin} [built]

┗ ----------------------------
┏ Renderer -------------------

  i ｢wdm｣: Compiled successfully.

┗ ----------------------------
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (d:\Agora-Electron-Quickstart\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (d:\Agora-Electron-Quickstart\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at startElectron (d:\Agora-Electron-Quickstart\node_modules\electron-webpack\src\dev\dev-runner.ts:156:33)
    at DevRunner.start (d:\Agora-Electron-Quickstart\node_modules\electron-webpack\src\dev\dev-runner.ts:67:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)

我又重新来了一遍... 上次好像是这个报错   @@我把electron删了重新装的，我现在还需要这么做么？help.....Thanks.~~~

@plutoless

**Comment by plutoless** [comment]
https://github.com/electron/electron/issues/8466
electron没装好，建议国内安装用镜像 
https://blog.yasking.org/a/zh-install-electron-development.html

**Comment by kongliya** [comment]
好的，我去试试，感谢大佬，手动抱拳。 (*^▽^*) @plutoless

**Comment by winghua** [comment]
![1](https://user-images.githubusercontent.com/30567528/67557519-d59bb180-f747-11e9-921d-d12934da538b.png)
window 用electron-vue的，报这个错误
